package com.sepnotican.agi.core.form.generic;

import com.sepnotican.agi.core.annotations.AgiUI;
import com.sepnotican.agi.core.annotations.BigString;
import com.sepnotican.agi.core.annotations.LinkedObject;
import com.sepnotican.agi.core.annotations.Synonym;
import com.sepnotican.agi.core.form.IFormHandler;
import com.sepnotican.agi.core.utils.UIOrderComparator;
import com.vaadin.data.Binder;
import com.vaadin.data.HasValue;
import com.vaadin.data.converter.StringToDoubleConverter;
import com.vaadin.data.converter.StringToFloatConverter;
import com.vaadin.data.converter.StringToLongConverter;
import com.vaadin.icons.VaadinIcons;
import com.vaadin.ui.*;
import org.slf4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Scope;
import org.springframework.data.jpa.repository.JpaRepository;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.stream.Collectors;

@org.springframework.stereotype.Component
@Scope("prototype")
public class AbstractElementForm<T> extends VerticalLayout {

    @Value("${agi.forms.element.save}")
    private String BTN_SAVE_TEXT;
    @Value("${agi.forms.element.reload}")
    private String BTN_RELOAD_TEXT;
    @Value("${agi.forms.element.enum-null-selection}")
    private String EMPTY_ENUM_TEXT;
    @Autowired
    private Logger logger;
    protected T entity;
    protected Binder<T> binder;
    protected Layout defaultControlPanel;
    protected IFormHandler formHandler;
    protected String formCachedName;

    @Autowired
    private ApplicationContext context;

    private JpaRepository<T, Object> repository;

    public AbstractElementForm(IFormHandler formHandler, JpaRepository<T, Object> repository) {
        this.repository = repository;
        this.formHandler = formHandler;
    }

    public void init(T entity, boolean isNewInstance, String formCachedName) {
        this.formCachedName = formCachedName;
        removeAllComponents();

        this.entity = entity;
        binder = new Binder(entity.getClass());

        initDefaultControlPanel(binder);

        Class clazz = entity.getClass();
        Field[] fieldsArray = clazz.getDeclaredFields();
        ArrayList<Field> fieldArrayList = createOrderedElementsList(fieldsArray);

        for (Field field : fieldArrayList) {

            Component component = getComponentByFieldAndBind(field, binder);

            if (component == null) continue;

            if (field.isAnnotationPresent(javax.persistence.Id.class))
                ((HasValue) component).setReadOnly(true);

            makeUpCaptionForField(field, component);
            addComponent(component);
            component.setWidth(40f, Unit.PERCENTAGE);
        }
        binder.bindInstanceFields(entity);
        if (!isNewInstance) binder.readBean(entity);
    }

    protected ArrayList<Field> createOrderedElementsList(Field[] fieldsArray) {
        return Arrays.stream(fieldsArray)
                .sorted(new UIOrderComparator()).collect(Collectors.toCollection(ArrayList::new));
    }

    protected void initDefaultControlPanel(Binder<T> binder) {
        defaultControlPanel = new HorizontalLayout();
        MenuBar menuBar = new MenuBar();
        createSaveButton(binder, menuBar);
        createReloadButton(binder, menuBar);
        defaultControlPanel.addComponent(menuBar);
        addComponent(defaultControlPanel);
    }

    protected void createReloadButton(Binder<T> binder, MenuBar menuBar) {
        menuBar.addItem(BTN_RELOAD_TEXT,
                VaadinIcons.REFRESH,
                event -> binder.readBean(entity));
    }

    protected void createSaveButton(Binder<T> binder, MenuBar menuBar) {
        menuBar.addItem(BTN_SAVE_TEXT,
                VaadinIcons.CHECK,
                event -> {
                    try {
                        binder.writeBean(entity);
                        repository.save(entity);
                        binder.readBean(entity); //reload autogenerated fields
                        formHandler.refreshElementCaption(entity, formCachedName);
                    } catch (Exception e) {
                        Notification.show("Error", "Error while saving element", Notification.Type.ERROR_MESSAGE);
                        logger.error("Error while saving element: " + entity.getClass().getCanonicalName());
                    }
                });
    }

    protected void makeUpCaptionForField(Field field, Component component) {
        if (field.isAnnotationPresent(Synonym.class)) {
            component.setCaption(field.getAnnotation(Synonym.class).value());
        } else component.setCaption(field.getName());
    }

    protected Component getComponentByFieldAndBind(Field field, Binder binder) {
        if (field.getType().equals(Long.class)
                || field.getType().equals(long.class)) {
            return generateLongField(field, binder);

        } else if (field.getType().equals(Double.class)
                || field.getType().equals(double.class)) {
            return generateDoubleFieild(field, binder);

        } else if (field.getType().equals(Float.class)
                || field.getType().equals(float.class)) {
            return generateFloatFieild(field, binder);

        } else if (field.getType().equals(String.class)) {
            return generateStringField(field, binder);

        } else if (field.getType().isEnum()) {
            return generateEnumField(field, binder);

        } else return generateLinkedObjectField(field, binder);
    }

    protected Component generateFloatFieild(Field field, Binder binder) {
        TextField textField = new TextField(field.getName());
        binder.forField(textField)
                .withConverter(new StringToFloatConverter("Must be a float value"))
                .bind(field.getName());
        return textField;
    }

    protected Component generateDoubleFieild(Field field, Binder binder) {
        TextField textField = new TextField(field.getName());
        binder.forField(textField)
                .withConverter(new StringToDoubleConverter("Must be a double value"))
                .bind(field.getName());
        return textField;
    }

    protected Component generateEnumField(Field field, Binder binder) {
        ComboBox comboBox = new ComboBox<>();
        comboBox.setEmptySelectionCaption(EMPTY_ENUM_TEXT);
        comboBox.setItems(field.getType().getEnumConstants());
        binder.bind(comboBox, field.getName());
        return comboBox;
    }

    protected Component generateStringField(Field field, Binder binder) {

        Component textField = null;
        if (field.isAnnotationPresent(BigString.class)) {
            textField = new TextArea();
        } else textField = new TextField();
        binder.bind((HasValue) textField, field.getName());
        return textField;
    }

    protected Component generateLongField(Field field, Binder binder) {
        TextField textField = new TextField(field.getName());
        binder.forField(textField)
                .withConverter(new StringToLongConverter("Must be a Long value"))
                .bind(field.getName());
        return textField;
    }

    protected Component generateLinkedObjectField(Field field, Binder binder) {

        if (!field.isAnnotationPresent(LinkedObject.class)) return null;
        if (!field.getType().isAnnotationPresent(AgiUI.class)) {
            logger.warn("Attempt to create field without AgiUI annotation. " +
                    "\nClassname = " + field.getClass().getCanonicalName() +
                    "\nField name = " + field.getName());
            return null;
        }

        Class repositoryClass = field.getType().getAnnotation(AgiUI.class).repo();
        JpaRepository repository = (JpaRepository) context.getBean(repositoryClass);

        ComboBox comboBox = new ComboBox<>();
        comboBox.setEmptySelectionCaption(EMPTY_ENUM_TEXT);
        comboBox.setItems(repository.findAll());

        binder.bind(comboBox, field.getName());
        return comboBox;
    }
}
