# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: agi-db1
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 159159
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
