package com.sepnotican.springjpaformautocreator;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class AutoGeneratedInterfaceApplication {

    public static void main(String[] args) {
        SpringApplication.run(AutoGeneratedInterfaceApplication.class, args);
    }
}
